


/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/


object Prob045 {
  def main(args: Array[String]) {

    def tri(n:Int)  = (n*(n+1))/2
    def pent(n:Int) = (n*(3*n-1))/2
    def hex(n:Int)  = n*(2*n-1)

    println("Verify that tri(285) = %d = pent(165) = %d = hex(143) = %d".format(tri(285),pent(165),hex(143)))

    var foundIt = false
    var n = 10 //144
    val h = hex(n)
    var k = 1
    val pk = pent(k)
    var j = 1
    val tj = tri(j)


    while (!foundIt) {
      val h = hex(n)
       println("h = "+h)

      while (pk <= h) {
        if (pk != h) {
          k += 1
          val pk = pent(k)
          println("pk = "+pk)
        }
        else {

          while (tj <= h) {
            if (tj != h) {
              j += 1
              val tj = tri(j)
              println("tj = "+tj)
            }
            else foundIt = true
          }
        }
      }
      n += 1
    }

    println("tri(%d) = pent(%d) = hex(%d) = %d".format(j,k,n,h))
  }
}